# Uncomment the next line to define a global platform for your project
platform :ios, '11.0'
inhibit_all_warnings!

target 'TEDY-Makeathon' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TEDY-Makeathon
  pod 'Material'
  pod 'SCLAlertView'
end
